[build]
beforeDevCommand = "yarn dev"
beforeBuildCommand = "yarn build"
devPath = "http://localhost:1420"
distDir = "../dist"
withGlobalTauri = false

[package]
productName = "ellisia"
version = "0.0.0"

[tauri.allowlist]
all = false
path = { all = true }

[tauri.allowlist.shell]
all = false
open = true

[tauri.bundle]
active = true
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico"
]
identifier = "com.balthild.ellisia"
targets = "all"

[tauri.security]
# csp = ''

[tauri.updater]
active = false

#[[tauri.windows]]
#fullscreen = false
#resizable = true
#title = "Ellisia"
#minWidth = 900
#minHeight = 800
